version: '3'

services:
  backend:
    build: ./BDIS_landing_back
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
  
  postgres:
    image: postgres:latest
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
  frontend:
    build: ./BDIS_landing_front
    ports:
      - "3000:3000"
  
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/local/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
